services:
  app:
    build: .
    ports:
      - "5555:5555"
    links:
      - pg
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - PROJECT_NAME=fastapi-arch-tmpl
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app_db
      - AUTO_RELOAD=true
      - DEBUG=true
    command: bash -c "alembic upgrade head && python3 manage.py runserver"
    volumes:
      - .:/app/

  pg:
    image: postgres:11.15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d app_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
