version: "2.1"

services:
  app:
    build: .
    ports:
      - "5555:5555"
    links:
      - pg
    tty: true
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - PROJECT_NAME=fastapi-arch-tmpl
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_db
    volumes:
      - .:/app/

  pg:
    image: postgres:11.15
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
