FROM locustio/locust:2.28.0

WORKDIR /mnt/locust

RUN pip3 install \
    Faker==13.3.4 \
    factory-boy==3.2.1 \
    polyfactory==2.16.0 \
    sqlalchemy==2.0.30 \
    pydantic==2.7.1 \
    sqlmodel==0.0.18

COPY . .
