services:
  app:
    build: .
    ports:
      - "5555:5555"
    links:
      - pg
    tty: true
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - PROJECT_NAME=fastapi-arch-tmpl
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_db
      - RMQ_USER=pog7x
      - RMQ_PASSWORD=pass
      - RMQ_HOST=rmq
      - RMQ_PORT=5672
      - RMQ_VHOST=/
      - RMQ_EXCHANGE=publish.consume.coffee.testing.exchange
      - RMQ_ROUTING_KEY=publish.consume.coffee.testing.key
      - RMQ_QUEUE=publish.consume.coffee.testing.queue
    volumes:
      - .:/app/

  pg:
    image: postgres:11.15
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
