"""init

Revision ID: 0001
Revises: 
Create Date: 2023-01-29 19:10:02.394110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('blend_name', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('intensifier', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('social_insurance_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('employment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('coffee')
    # ### end Alembic commands ###
